theme: jekyll-theme-minimal
title: [Dominik Senti]
description: [Welcome to my personal website!

This page is meant as a way to provide a short description of who I am. I have included a few links where you can find more information about myself.]
logo: /assets/facebookpp.jpg
