theme: jekyll-theme-minimal
title: [Dominik Senti]
description: [this is a short summary of who I am with links to relevant pages.]
logo: [https://github.com/dsenti/dsenti.github.io/blob/f57505e855af99b2a34593344a4ed1d02a994bf4/facebookpp.jpg]
